CREATE SEQUENCE IF NOT EXISTS seq_job;

CREATE TABLE IF NOT EXISTS job
(
    id   BIGINT UNIQUE       NOT NULL DEFAULT NEXTVAL('seq_job'),
    name VARCHAR(200) UNIQUE NOT NULL,

    CONSTRAINT cor_pk_id PRIMARY KEY (id)
);
