server:
  port: 8080
  servlet:
    context-path: /fisa-ssm

spring:
  task:
    execution:
      thread-name-prefix: task-fisa-ssm
      pool:
        queue-capacity: 50
        max-size: 20
        core-size: 10
        allow-core-thread-timeout: true
        keep-alive: 30s

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB
      enabled: true
  flyway:
    enabled: true
    clean-disabled: false
    clean-on-validation-error: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    encoding: UTF-8
    baseline-on-migrate: true
    baseline-version: 1
  datasource:
    url: jdbc:postgresql://localhost:5432/fisa-ssm
    password: root
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: ${spring.jpa.database-platform}
        #        show_sql: ${spring.jpa.show-sql}
        format_sql: ${spring.jpa.show-sql}
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
  security:
    cors:
      origin: 'http://localhost:3000'
      allow-credentials: true
      allowed-methods: GET, POST, PUT, DELETE, HEAD, PATCH, OPTIONS
      allowed-headers: Origin, Accept, Content-Type, Cookie
      expose-headers: Content-Type
      max-age: 3600
    jwt:
      expiration: 3600
      cookie:
        client-domain: 'localhost'
        name: JwtAuth
        secure: false
        http-only: true
        path: /
        same-site: strict
        priority: High
        max-age: ${spring.security.jwt.expiration}
    user:
      password: ${INITIAL_PASSWORD}

logging:
  level:
    #    org.hibernate.sql: DEBUG
    org.springframework.security: DEBUG
#    org.springframework.transaction: TRACE
